import type { Metadata } from 'next';
import StyledComponentsRegistry from '@/app/registry';
import { GlobalStyle } from '@/theme/styles';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <GlobalStyle />
        {children}
      </StyledComponentsRegistry>
    </html>
  );
}
